module hibernate.validator {
    requires transitive classmate;
    requires hibernate.jpa;
    requires transitive java.desktop;
    requires transitive java.scripting;
    requires transitive java.xml;
    requires transitive java.xml.bind;
    requires transitive javafx.base;
    requires transitive javax.el;
    requires transitive jboss.logging;
    requires jboss.logging.annotations;
    requires transitive joda.time;
    requires jsoup;
    requires transitive money.api;
    requires transitive paranamer;
    requires transitive validation.api;
    exports org.hibernate.validator;
    exports org.hibernate.validator.cfg;
    exports org.hibernate.validator.cfg.context;
    exports org.hibernate.validator.cfg.defs;
    exports org.hibernate.validator.cfg.defs.br;
    exports org.hibernate.validator.cfg.defs.pl;
    exports org.hibernate.validator.constraints;
    exports org.hibernate.validator.constraints.br;
    exports org.hibernate.validator.constraints.pl;
    exports org.hibernate.validator.constraintvalidation;
    exports org.hibernate.validator.constraintvalidators;
    exports org.hibernate.validator.engine;
    exports org.hibernate.validator.group;
    exports org.hibernate.validator.internal.cfg.context;
    exports org.hibernate.validator.internal.constraintvalidators.bv;
    exports org.hibernate.validator.internal.constraintvalidators.bv.future;
    exports org.hibernate.validator.internal.constraintvalidators.bv.money;
    exports org.hibernate.validator.internal.constraintvalidators.bv.past;
    exports org.hibernate.validator.internal.constraintvalidators.bv.size;
    exports org.hibernate.validator.internal.constraintvalidators.hv;
    exports org.hibernate.validator.internal.constraintvalidators.hv.br;
    exports org.hibernate.validator.internal.constraintvalidators.hv.pl;
    exports org.hibernate.validator.internal.engine;
    exports org.hibernate.validator.internal.engine.constraintdefinition;
    exports org.hibernate.validator.internal.engine.constraintvalidation;
    exports org.hibernate.validator.internal.engine.groups;
    exports org.hibernate.validator.internal.engine.messageinterpolation;
    exports org.hibernate.validator.internal.engine.messageinterpolation.el;
    exports org.hibernate.validator.internal.engine.messageinterpolation.parser;
    exports org.hibernate.validator.internal.engine.path;
    exports org.hibernate.validator.internal.engine.resolver;
    exports org.hibernate.validator.internal.engine.time;
    exports org.hibernate.validator.internal.engine.valuehandling;
    exports org.hibernate.validator.internal.metadata;
    exports org.hibernate.validator.internal.metadata.aggregated;
    exports org.hibernate.validator.internal.metadata.aggregated.rule;
    exports org.hibernate.validator.internal.metadata.core;
    exports org.hibernate.validator.internal.metadata.descriptor;
    exports org.hibernate.validator.internal.metadata.facets;
    exports org.hibernate.validator.internal.metadata.location;
    exports org.hibernate.validator.internal.metadata.provider;
    exports org.hibernate.validator.internal.metadata.raw;
    exports org.hibernate.validator.internal.util;
    exports org.hibernate.validator.internal.util.annotationfactory;
    exports org.hibernate.validator.internal.util.classhierarchy;
    exports org.hibernate.validator.internal.util.logging;
    exports org.hibernate.validator.internal.util.logging.formatter;
    exports org.hibernate.validator.internal.util.privilegedactions;
    exports org.hibernate.validator.internal.util.scriptengine;
    exports org.hibernate.validator.internal.xml;
    exports org.hibernate.validator.internal.xml.binding;
    exports org.hibernate.validator.messageinterpolation;
    exports org.hibernate.validator.parameternameprovider;
    exports org.hibernate.validator.path;
    exports org.hibernate.validator.resourceloading;
    exports org.hibernate.validator.spi.cfg;
    exports org.hibernate.validator.spi.group;
    exports org.hibernate.validator.spi.resourceloading;
    exports org.hibernate.validator.spi.time;
    exports org.hibernate.validator.spi.valuehandling;
    exports org.hibernate.validator.valuehandling;
    provides javax.validation.spi.ValidationProvider with
        org.hibernate.validator.HibernateValidator;
}
