#
#  SPDX-License-Identifier: Apache-2.0
#
#   Copyright The original authors
#
#   Licensed under the Apache Software License version 2.0, available at http://www.apache.org/licenses/LICENSE-2.0
#

FROM moditect/vertx-helloworld-base

COPY maven/moditect-integrationtest-vertx-1.0.0-SNAPSHOT.jar /opt/upgrade-modules/
